# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tica < Formula
  desc ""
  homepage "https://github.com/gavasc/homebrew-taps"
  version "0.2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gavasc/tica/releases/download/v0.2.0/tica_Darwin_x86_64.tar.gz"
      sha256 "6a347236ae4e0f8300f959ea994a569f91a2e4215da091b7ffe992cab388635b"

      def install
        bin.install "tica"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/gavasc/tica/releases/download/v0.2.0/tica_Darwin_arm64.tar.gz"
      sha256 "3ecbb8652a317eba87e41b55a2c270795311980b479418881b02c9cf20016384"

      def install
        bin.install "tica"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gavasc/tica/releases/download/v0.2.0/tica_Linux_x86_64.tar.gz"
        sha256 "c4bcc29997ccb6fbb1364b6ac1e56c6e4c60d660dd480e5c49ddb344edfd4e57"

        def install
          bin.install "tica"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gavasc/tica/releases/download/v0.2.0/tica_Linux_arm64.tar.gz"
        sha256 "7a2269ea6c24751476f1397cbf7df48dba78a14ff2bc9907c70e14343c607b66"

        def install
          bin.install "tica"
        end
      end
    end
  end
end
