# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tica < Formula
  desc ""
  homepage "https://github.com/gavasc/homebrew-taps"
  version "0.1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gavasc/tica/releases/download/v0.1.1/tica_Darwin_x86_64.tar.gz"
      sha256 "11da8417a0688f566cebb90a5f916cc1e213a99d31f891c12d38f8fe5414e735"

      def install
        bin.install "tica"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/gavasc/tica/releases/download/v0.1.1/tica_Darwin_arm64.tar.gz"
      sha256 "eb5f276c29004807e2ad3152d23a039b54e62ce2a5072ad0a2df37f8d15a0045"

      def install
        bin.install "tica"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gavasc/tica/releases/download/v0.1.1/tica_Linux_x86_64.tar.gz"
        sha256 "4743923758293cc31c060b91d3f96b4bdfedd8e35deb276c5f35b72c6f77ff4d"

        def install
          bin.install "tica"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gavasc/tica/releases/download/v0.1.1/tica_Linux_arm64.tar.gz"
        sha256 "d52f57c02a7f5b5f329c2f4308ff2965a0159c462ffd701dceec10151748cb1a"

        def install
          bin.install "tica"
        end
      end
    end
  end
end
